security:
 token:
  secret: T6JY9jwA8sXJUJ8e
spring:
 datasource:
  url: jdbc:mariadb://nrffbltw99v3vk0j.myfritz.net:3306/leftlovers
  username: ll_db
  password: Start123
 jpa:
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
  hibernate:
   ddl-auto: none
server:
  context-path: /ChatService
endpoints:
  cors:
    allowed-origins: "*"
    allowed-methods: "*"
